version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka:2.11-1.1.1 #The spark consumer doesn't work with scala 2.12
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 185.185.126.143 
      KAFKA_CREATE_TOPICS: "Topic_A:1:1"  #docker template , topic not used
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  spark:
    image: jupyter/all-spark-notebook
    ports:
      - "8888:8888"
      - "4040-4080:4040-4080"
    links:
      - "kafka:kafka-server" #allows spark notebook to discover kafka service by name "kafka-server"
    volumes:
      - ../notebooks:/home/jovyan/work/notebooks/
  spark1:
    image: jupyter/all-spark-notebook
    ports:
      - "8889:8888"             #jupiter ui  exposing in different ports different ports
      - "5040-5080:4040-4080"   #spark ui 
    links:
      - "kafka:kafka-server" #allows spark notebook to discover kafka service by name "kafka-server"
    volumes:
      - ../notebooks1:/home/jovyan/work/notebooks/  
